apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: hive
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: manifests/
    repoURL: https://github.com/dgoodwin/hive-argocd-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
